### ISSUE TITLE
Use NIP-33 kind range

### ISSUE THREAD

**Issue by dskvr** [nodetec/notestack#70]
If you use `NIP-33` instead of a _regular kind_, blog posts can be editable.

Additionally, consider submitting a NIP so your posts are interoperable and can benefit from a network effect. Right now you're on an isolated island.

**Comment by ChristianChiarulli** [comment]
hey @dskvr I do want to make the posts editable but I'm still trying to come up with a good solution for this. I was playing around with nip33 for "bookmarks" or "lists" (https://github.com/nodetec/blogstack/pull/49) but I'm not sure I want to use it for the blogs because I'd like the links to blogs to always be static bech32 encoded note ids (this is subject to change if someone has a better well thought out standard for blogs).

As a quick an dirty workaround I've considered just deleting and reposting but that obviously doesn't solve my long term goal.

as far as being on an isolated network that's kinda on purpose for now until we have a solid NIP for blogs. I've been coming up with ideas but nothing I really like yet.

So far my idea for blogs is that they should be 

- their own kind
- editable (chain of edits where the first id is the master id and points to the most recently created e tag if available)
- should include a title indexable on `#title` like subject (which we're using as a pseudotitle for now)

let me know if you have any recommendations or ideas I'm still pretty new to nostr overall so it's still like drinking from a firehouse of information.

**Comment by dskvr** [comment]
> I'm not sure I want to use it for the blogs because I'd like the links to blogs to always be static bech32 encoded note ids (this is subject to change if someone has a better well thought out standard for blogs).

Check this out: https://github.com/nostr-protocol/nips/pull/220

You can persist the content id with the `d` tag, use other tags to retain certain meta data like the creation date

**Comment by ChristianChiarulli** [comment]
We're using the new 30023 kind for longform content
